#!/bin/bash
# TodoTracker Web Server Launcher
# Auto-generated by setup-project-todos.sh

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load configuration
CONFIG_FILE="$SCRIPT_DIR/.todos/config.json"

if [ ! -f "$CONFIG_FILE" ]; then
    echo "❌ Configuration file not found: $CONFIG_FILE"
    echo "   Please run setup-project-todos.sh first"
    exit 1
fi

# Extract TodoTracker path from config
TODOTRACKER_PATH=$(python3 -c "import json; print(json.load(open('$CONFIG_FILE'))['todotracker_path'])")

if [ ! -d "$TODOTRACKER_PATH" ]; then
    echo "❌ TodoTracker installation not found: $TODOTRACKER_PATH"
    echo "   Please reinstall TodoTracker or run setup-project-todos.sh again"
    exit 1
fi

# Change to project directory
cd "$SCRIPT_DIR"

# Set environment variables for this project
export TODOTRACKER_DB_PATH="$SCRIPT_DIR/.todos/project.db"
export TODOTRACKER_PROJECT_NAME="$(basename "$SCRIPT_DIR")"

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Launch the web server
echo "🚀 Launching TodoTracker Web Server..."
echo "📁 Project: $TODOTRACKER_PROJECT_NAME"
echo "📂 Database: $TODOTRACKER_DB_PATH"
echo ""

# Try uv first (preferred)
if command_exists uv; then
    echo "Using uv environment..."
    # Run from TodoTracker directory to use its dependencies
    cd "$TODOTRACKER_PATH"
    exec uv run --directory "$TODOTRACKER_PATH" python todotracker_webserver.py "$@"

# Fall back to virtual environment
elif [ -f "$TODOTRACKER_PATH/.venv/bin/python" ]; then
    echo "Using virtual environment..."
    exec "$TODOTRACKER_PATH/.venv/bin/python" "$TODOTRACKER_PATH/todotracker_webserver.py" "$@"

# Fall back to system Python
elif command_exists python3; then
    echo "Using system Python3..."
    # Add TodoTracker to Python path
    export PYTHONPATH="$TODOTRACKER_PATH:$PYTHONPATH"
    exec python3 "$TODOTRACKER_PATH/todotracker_webserver.py" "$@"

# No Python found
else
    echo "❌ No Python environment found!"
    echo "Please install Python 3.10+ and set up TodoTracker properly."
    exit 1
fi
